# Generated by Django 4.1.3 on 2022-11-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
