# Generated by Django 4.1.3 on 2022-11-13 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_alter_ticket_reply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reply_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='support_response',
            field=models.TextField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
