# Generated by Django 4.1.3 on 2022-11-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_alter_comments_reply_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Ticket.ticket'),
        ),
    ]
