# Generated by Django 4.1.3 on 2022-11-16 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0005_alter_comments_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Ticket.ticket'),
        ),
    ]
