# Generated by Django 4.1.3 on 2022-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0006_alter_comments_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='support_id',
            field=models.IntegerField(null=True),
        ),
    ]
