# Generated by Django 4.1.3 on 2022-11-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0007_comments_support_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_comment',
        ),
    ]
