# Generated by Django 4.1.3 on 2022-12-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0008_remove_ticket_is_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['comment_date']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['message_date']},
        ),
    ]
